inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'test_redis_failover.rb'

# I never write any, so don't bug me about it
Documentation:
  Enabled: false

# SOIDs don't need commas
NumericLiterals:
  MinDigits: 14

# 80 is rather short
#LineLength:
#  Max: 120
