source 'https://rubygems.org'

gem 'bundler'
gem 'rake'
gem 'bson_ext'
gem 'bson'
gem 'mongoid', '~> 3.1.6'
gem 'mongoid-pagination'
gem 'sidekiq'
gem 'newrelic_rpm'
gem 'sinatra'
gem 'foreman', '~> 0.63.0'
gem 'puma', '~> 2.9.2'
gem 'eventmachine'
gem 'hipchat'
gem 'erubis'
gem 'redis-sentinel'
gem 'grape'
gem 'grape-entity'
gem 'grape-swagger' # , path: '../grape-swagger/'
gem 'roar'
gem 'rack-contrib'
gem 'diplomat'
gem 'rack-cors'

group :development  do
end

group :test do
  gem 'rspec'
  gem 'rspec_junit_formatter'
  gem 'gem-release'
  gem 'vcr'
  gem 'webmock'
  gem 'rack-test'
  gem 'simplecov'
  gem 'rubocop'
  gem 'bump'
  gem 'mongoid-rspec', '~> 1.13.0'
end
